# Generated by Django 5.2.4 on 2025-07-29 21:51

import django.db.models.deletion
import producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=11)),
                ("cantidad", models.IntegerField()),
                (
                    "imagen1",
                    models.ImageField(upload_to=producto.models.producto_image_path),
                ),
                (
                    "imagen2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=producto.models.producto_image_path,
                    ),
                ),
                (
                    "imagen3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=producto.models.producto_image_path,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="producto.categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="producto.marca",
                    ),
                ),
            ],
        ),
    ]
