# Generated by Django 5.2.7 on 2025-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_usuario_atributos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("", "Seleccione un rol"),
                    (1, "Administrador"),
                    (2, "Empleado"),
                    (3, "Cliente"),
                ],
                default=3,
                null=True,
            ),
        ),
    ]
