# Generated by Django 5.2.7 on 2025-10-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_alter_usuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="token",
            field=models.TextField(default=None),
        ),
    ]
