# Generated by Django 5.2.4 on 2025-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_pasarela_alter_venta_pasarela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasarela',
            name='contexto',
            field=models.TextField(blank=True, default={}, null=True),
        ),
    ]
