# Generated by Django 5.2.4 on 2025-09-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0003_alter_pasarela_contexto"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="atributos",
            field=models.TextField(default={}),
        ),
    ]
