# Generated by Django 5.2.4 on 2025-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0004_venta_atributos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha_creacion",
            field=models.DateTimeField(),
        ),
    ]
